# Generated by Django 3.2.4 on 2021-06-19 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_task', models.TextField(blank=True)),
                ('task', models.TextField(blank=True)),
                ('ccq', models.TextField(blank=True)),
                ('warmup', models.TextField(blank=True)),
                ('lesson_link', models.TextField(blank=True)),
                ('outline', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('private', models.BooleanField(default=True)),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Uncategorized', 'Un'), ('Beginner (A0)', 'A0'), ('High Beginner (A1)', 'A1'), ('Low Intermediate (A2)', 'A2'), ('Intemediate (B1)', 'B1'), ('High Intermediate (B2)', 'B2'), ('Advanced (C1)', 'C1'), ('High Advanced (C2)', 'C2')], default='Uncategorized', max_length=30), size=None)),
            ],
        ),
    ]
