# Generated by Django 3.2.4 on 2021-06-27 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plan', '0002_lessonplan_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='ccq',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='outline',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='pre_task',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='task',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='warmup',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=None, size=None),
            preserve_default=False,
        ),
    ]
