# Generated by Django 3.2.4 on 2021-06-27 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plan', '0003_auto_20210627_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
