# Generated by Django 3.2.4 on 2021-06-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20210627_1347'),
        ('student', '0002_initial'),
        ('feedback', '0003_feedback_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
