# Generated by Django 3.2.4 on 2021-06-21 17:05

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('occupation', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('level', models.CharField(blank=True, choices=[('Uncategorized', 'Un'), ('Beginner (A0)', 'A0'), ('High Beginner (A1)', 'A1'), ('Low Intermediate (A2)', 'A2'), ('Intemediate (B1)', 'B1'), ('High Intermediate (B2)', 'B2'), ('Advanced (C1)', 'C1'), ('High Advanced (C2)', 'C2')], default='Uncategorized', max_length=30, null=True)),
                ('L1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l1_student', to='utilities.language')),
                ('L2', models.ManyToManyField(blank=True, related_name='l2_student1', to='utilities.Language')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.company')),
            ],
        ),
    ]
