# Generated by Django 3.2.4 on 2021-06-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210621_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
