# Generated by Django 3.2.4 on 2021-06-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
        ('lesson', '0001_initial'),
        ('lesson_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lesson_plan.lessonplan'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ManyToManyField(to='utilities.Subject'),
        ),
    ]
