# Generated by Django 3.2.4 on 2021-06-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('lesson', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
