# Generated by Django 3.2.4 on 2021-06-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('lesson', '0002_lesson_lesson_plan'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ManyToManyField(blank=True, to='utilities.Subject'),
        ),
    ]
