# Generated by Django 3.2.4 on 2021-06-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.student'),
        ),
    ]
