# Generated by Django 3.2.4 on 2021-06-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plan', '0002_lessonplan_teacher'),
        ('lesson', '0004_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson', to='lesson_plan.lessonplan'),
        ),
    ]
