# Generated by Django 3.2.4 on 2021-06-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_options'),
        ('lesson', '0005_auto_20210621_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
