# Generated by Django 3.2.4 on 2021-06-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plan', '0003_auto_20210627_1347'),
        ('lesson', '0005_alter_lesson_lesson_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='lesson_plan.lessonplan'),
        ),
    ]
