# Generated by Django 3.2.4 on 2021-06-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_alter_lesson_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
