# Generated by Django 3.2.4 on 2021-06-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('name',)},
        ),
    ]
